FROM node:22.17.0-alpine

RUN corepack enable
RUN yarn set version 4.9.2
WORKDIR /app

COPY package.json .yarnrc.yml yarn.lock .pnp.cjs .pnp.loader.mjs ./
RUN yarn install --immutable

COPY . ./
RUN yarn build --mode development

ENV NODE_ENV=development
ENV SERVE_API=local
ENV PORT=5173
EXPOSE 5173
CMD ["sh", "-c", "yarn dev --port $PORT --host 0.0.0.0"]