FROM python:3.13-slim

ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN pip install poetry && \
    poetry install \
    --no-root \
    --no-interaction \
    --no-ansi \

COPY . /app/

RUN pip install .

CMD ["poetry", "run", "uvicorn", "mail_service_contact_form.main:app"]