spring:
  application:
    name: contact-form-mail
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    de.bot.pilot.mail: ${LOG_LEVEL_MAIL:INFO}
management:
  endpoints:
    web:
      exposure:
        include: "health"