spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: contact-form-mail
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
logging:
  level:
    de.bot.pilot.mail: ${LOG_LEVEL_MAIL:INFO}
management:
  endpoints:
    web:
      exposure:
        include: "health"

captcha:
  secret:
    path: ${CAPTCHA_SECRET_PATH}