FROM node:22.17.0-alpine AS builder
RUN corepack enable
WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.yarn/berry/cache \
    yarn install --immutable && \
    yarn build --mode development

# 2. Stage: Runner
FROM nginx:stable-alpine AS runner

COPY --from=builder /app/dist /usr/share/nginx/html

# COPY deployment/dev/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]