FROM node:22.17.0-alpine AS builder
RUN corepack enable
WORKDIR /app

COPY . .

RUN yarn set version 4.9.2
RUN yarn install --immutable && \
    yarn build --mode production

# 2. Stage: Runner
FROM nginx:stable-alpine AS runner

COPY --from=builder /app/dist /usr/share/nginx/html

# COPY deployment/dev/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]